[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm = { version = "0.4.1", features = ["bn254"] }

sled = "0.34.6"
blake2 = "0.9.1"
dirs = "3.0"
downloader = { version = "0.2.7", optional = true, default-features = false, features = ["rustls-tls"] }
indicatif = "0.15.0"
regex = "1.4.0"

[features]
# This feature flag is here because we cannot compile
# the downloader dependency with the wasm32 target
default = ["std"]
std = ["downloader"]
